// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_grpc.proto

package examplePb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyReqMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReqMsg) Reset()         { *m = EmptyReqMsg{} }
func (m *EmptyReqMsg) String() string { return proto.CompactTextString(m) }
func (*EmptyReqMsg) ProtoMessage()    {}
func (*EmptyReqMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_804d5c0a5eff92d4, []int{0}
}

func (m *EmptyReqMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReqMsg.Unmarshal(m, b)
}
func (m *EmptyReqMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReqMsg.Marshal(b, m, deterministic)
}
func (m *EmptyReqMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReqMsg.Merge(m, src)
}
func (m *EmptyReqMsg) XXX_Size() int {
	return xxx_messageInfo_EmptyReqMsg.Size(m)
}
func (m *EmptyReqMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReqMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReqMsg proto.InternalMessageInfo

type CommonRespMsg struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRespMsg) Reset()         { *m = CommonRespMsg{} }
func (m *CommonRespMsg) String() string { return proto.CompactTextString(m) }
func (*CommonRespMsg) ProtoMessage()    {}
func (*CommonRespMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_804d5c0a5eff92d4, []int{1}
}

func (m *CommonRespMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRespMsg.Unmarshal(m, b)
}
func (m *CommonRespMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRespMsg.Marshal(b, m, deterministic)
}
func (m *CommonRespMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRespMsg.Merge(m, src)
}
func (m *CommonRespMsg) XXX_Size() int {
	return xxx_messageInfo_CommonRespMsg.Size(m)
}
func (m *CommonRespMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRespMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRespMsg proto.InternalMessageInfo

func (m *CommonRespMsg) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type FooReqMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooReqMsg) Reset()         { *m = FooReqMsg{} }
func (m *FooReqMsg) String() string { return proto.CompactTextString(m) }
func (*FooReqMsg) ProtoMessage()    {}
func (*FooReqMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_804d5c0a5eff92d4, []int{2}
}

func (m *FooReqMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooReqMsg.Unmarshal(m, b)
}
func (m *FooReqMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooReqMsg.Marshal(b, m, deterministic)
}
func (m *FooReqMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooReqMsg.Merge(m, src)
}
func (m *FooReqMsg) XXX_Size() int {
	return xxx_messageInfo_FooReqMsg.Size(m)
}
func (m *FooReqMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FooReqMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FooReqMsg proto.InternalMessageInfo

func (m *FooReqMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FooRespMsg struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooRespMsg) Reset()         { *m = FooRespMsg{} }
func (m *FooRespMsg) String() string { return proto.CompactTextString(m) }
func (*FooRespMsg) ProtoMessage()    {}
func (*FooRespMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_804d5c0a5eff92d4, []int{3}
}

func (m *FooRespMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooRespMsg.Unmarshal(m, b)
}
func (m *FooRespMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooRespMsg.Marshal(b, m, deterministic)
}
func (m *FooRespMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooRespMsg.Merge(m, src)
}
func (m *FooRespMsg) XXX_Size() int {
	return xxx_messageInfo_FooRespMsg.Size(m)
}
func (m *FooRespMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FooRespMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FooRespMsg proto.InternalMessageInfo

func (m *FooRespMsg) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type BarReqMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarReqMsg) Reset()         { *m = BarReqMsg{} }
func (m *BarReqMsg) String() string { return proto.CompactTextString(m) }
func (*BarReqMsg) ProtoMessage()    {}
func (*BarReqMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_804d5c0a5eff92d4, []int{4}
}

func (m *BarReqMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarReqMsg.Unmarshal(m, b)
}
func (m *BarReqMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarReqMsg.Marshal(b, m, deterministic)
}
func (m *BarReqMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarReqMsg.Merge(m, src)
}
func (m *BarReqMsg) XXX_Size() int {
	return xxx_messageInfo_BarReqMsg.Size(m)
}
func (m *BarReqMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BarReqMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BarReqMsg proto.InternalMessageInfo

func (m *BarReqMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BarRespMsg struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarRespMsg) Reset()         { *m = BarRespMsg{} }
func (m *BarRespMsg) String() string { return proto.CompactTextString(m) }
func (*BarRespMsg) ProtoMessage()    {}
func (*BarRespMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_804d5c0a5eff92d4, []int{5}
}

func (m *BarRespMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarRespMsg.Unmarshal(m, b)
}
func (m *BarRespMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarRespMsg.Marshal(b, m, deterministic)
}
func (m *BarRespMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarRespMsg.Merge(m, src)
}
func (m *BarRespMsg) XXX_Size() int {
	return xxx_messageInfo_BarRespMsg.Size(m)
}
func (m *BarRespMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BarRespMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BarRespMsg proto.InternalMessageInfo

func (m *BarRespMsg) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*EmptyReqMsg)(nil), "EmptyReqMsg")
	proto.RegisterType((*CommonRespMsg)(nil), "CommonRespMsg")
	proto.RegisterType((*FooReqMsg)(nil), "FooReqMsg")
	proto.RegisterType((*FooRespMsg)(nil), "FooRespMsg")
	proto.RegisterType((*BarReqMsg)(nil), "BarReqMsg")
	proto.RegisterType((*BarRespMsg)(nil), "BarRespMsg")
}

func init() { proto.RegisterFile("example_grpc.proto", fileDescriptor_804d5c0a5eff92d4) }

var fileDescriptor_804d5c0a5eff92d4 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x69, 0x57, 0x8a, 0x9d, 0xb5, 0x05, 0x07, 0x11, 0x59, 0xa1, 0x48, 0x28, 0xe8, 0x29,
	0x82, 0xfe, 0x83, 0x95, 0xf6, 0x56, 0x28, 0xf1, 0xe6, 0x45, 0xd2, 0xed, 0x10, 0x02, 0xcd, 0x4e,
	0x4c, 0xa2, 0xd8, 0x7f, 0x2f, 0xa4, 0x65, 0x5d, 0x41, 0x3d, 0x86, 0x97, 0x79, 0x7c, 0xdf, 0x03,
	0xa4, 0x4f, 0xed, 0xfc, 0x8e, 0x5e, 0x4d, 0xf0, 0x8d, 0xf4, 0x81, 0x13, 0x8b, 0x09, 0x94, 0x0b,
	0xe7, 0xd3, 0x5e, 0xd1, 0xdb, 0x2a, 0x1a, 0x71, 0x0b, 0x93, 0x27, 0x76, 0x8e, 0x5b, 0x45, 0xd1,
	0xaf, 0xa2, 0xc1, 0x4b, 0x18, 0x05, 0x8a, 0xef, 0xbb, 0x74, 0x35, 0xb8, 0x19, 0xdc, 0x9d, 0xaa,
	0xe3, 0x4b, 0x5c, 0xc3, 0x78, 0xc9, 0x7c, 0xb8, 0xc2, 0x29, 0x0c, 0xed, 0x36, 0x7f, 0x28, 0xd4,
	0xd0, 0x6e, 0xc5, 0x1c, 0x20, 0x87, 0xbf, 0x55, 0x8c, 0xfb, 0x15, 0xb5, 0x0e, 0x7f, 0x57, 0xe4,
	0xf0, 0x5f, 0x8a, 0x87, 0x3d, 0x9c, 0x2f, 0x0e, 0x4e, 0xca, 0x37, 0xcf, 0x14, 0x3e, 0x6c, 0x43,
	0x38, 0x87, 0x93, 0xb5, 0x6d, 0x0d, 0x9e, 0xc9, 0x9e, 0x59, 0x35, 0x95, 0x3f, 0xc5, 0x66, 0x50,
	0x2c, 0x99, 0x11, 0x64, 0xa7, 0x51, 0x95, 0xb2, 0x47, 0x3d, 0x83, 0xa2, 0xd6, 0x01, 0x41, 0x76,
	0x8c, 0x55, 0x29, 0xbf, 0x91, 0xea, 0x8b, 0x17, 0x34, 0xd4, 0x52, 0xd0, 0x89, 0xee, 0x8f, 0xbb,
	0xae, 0x37, 0x9b, 0x51, 0x5e, 0xf5, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x8d, 0x21, 0xc2,
	0x6b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleRpcServiceClient is the client API for ExampleRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleRpcServiceClient interface {
	Ping(ctx context.Context, in *EmptyReqMsg, opts ...grpc.CallOption) (*CommonRespMsg, error)
	Foo(ctx context.Context, in *FooReqMsg, opts ...grpc.CallOption) (*FooRespMsg, error)
	Bar(ctx context.Context, in *BarReqMsg, opts ...grpc.CallOption) (*BarRespMsg, error)
}

type exampleRpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleRpcServiceClient(cc *grpc.ClientConn) ExampleRpcServiceClient {
	return &exampleRpcServiceClient{cc}
}

func (c *exampleRpcServiceClient) Ping(ctx context.Context, in *EmptyReqMsg, opts ...grpc.CallOption) (*CommonRespMsg, error) {
	out := new(CommonRespMsg)
	err := c.cc.Invoke(ctx, "/ExampleRpcService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleRpcServiceClient) Foo(ctx context.Context, in *FooReqMsg, opts ...grpc.CallOption) (*FooRespMsg, error) {
	out := new(FooRespMsg)
	err := c.cc.Invoke(ctx, "/ExampleRpcService/Foo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleRpcServiceClient) Bar(ctx context.Context, in *BarReqMsg, opts ...grpc.CallOption) (*BarRespMsg, error) {
	out := new(BarRespMsg)
	err := c.cc.Invoke(ctx, "/ExampleRpcService/Bar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleRpcServiceServer is the server API for ExampleRpcService service.
type ExampleRpcServiceServer interface {
	Ping(context.Context, *EmptyReqMsg) (*CommonRespMsg, error)
	Foo(context.Context, *FooReqMsg) (*FooRespMsg, error)
	Bar(context.Context, *BarReqMsg) (*BarRespMsg, error)
}

// UnimplementedExampleRpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExampleRpcServiceServer struct {
}

func (*UnimplementedExampleRpcServiceServer) Ping(ctx context.Context, req *EmptyReqMsg) (*CommonRespMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedExampleRpcServiceServer) Foo(ctx context.Context, req *FooReqMsg) (*FooRespMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Foo not implemented")
}
func (*UnimplementedExampleRpcServiceServer) Bar(ctx context.Context, req *BarReqMsg) (*BarRespMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bar not implemented")
}

func RegisterExampleRpcServiceServer(s *grpc.Server, srv ExampleRpcServiceServer) {
	s.RegisterService(&_ExampleRpcService_serviceDesc, srv)
}

func _ExampleRpcService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReqMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleRpcServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExampleRpcService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleRpcServiceServer).Ping(ctx, req.(*EmptyReqMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleRpcService_Foo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FooReqMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleRpcServiceServer).Foo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExampleRpcService/Foo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleRpcServiceServer).Foo(ctx, req.(*FooReqMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleRpcService_Bar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarReqMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleRpcServiceServer).Bar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExampleRpcService/Bar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleRpcServiceServer).Bar(ctx, req.(*BarReqMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleRpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExampleRpcService",
	HandlerType: (*ExampleRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ExampleRpcService_Ping_Handler,
		},
		{
			MethodName: "Foo",
			Handler:    _ExampleRpcService_Foo_Handler,
		},
		{
			MethodName: "Bar",
			Handler:    _ExampleRpcService_Bar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example_grpc.proto",
}
